version: 0.2

phases:
  build:
    commands:
      - cd talleres/07/
      - aws cloudformation validate-template --template-body file://api-cfn-pipeline.yaml

artifacts:
  # Archivos a exportar
  discard-paths: yes
  files:
    - talleres/07/api-cfn-pipeline.yaml